# Window
SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500
SCREEN_TITLE = "Tic Tac Toe"

# Board
BOARD_SIZE = 3
SQUARE_SIZE = SCREEN_WIDTH // BOARD_SIZE
CELL_PADDING = 20
LINE_WIDTH = 1

# Menu
MENU_WIDTH = 220
MENU_HEIGHT = 240

# Button
BUTTON_WIDTH = 180
BUTTON_HEIGHT = 40
GAP_BETWEEN_BUTTONS = 20

# Dialog
POPUP_WIDTH = 300
POPUP_HEIGHT = 220

# Game
X_PATTERN = 1
O_PATTERN = 2